spring:
  application:
    name: HFT Server
  config:
    import: "file:./secrets/secrets.yaml"

logging:
  level:
    root: INFO
    io.github.seokhyunpark.hft: DEBUG

hft:
  stream:
    market-uri: wss://data-stream.binance.vision:443/ws/btcfdusd@depth20@100ms
    user-uri: wss://ws-api.binance.com:443/ws-api/v3

  exchange:
    api-key: ""
    private-key-path: "./secrets/private_key.pem"

  websocket:
    enabled: true

  trading:
    symbol: BTCFDUSD
    base-asset: BTC
    quote-asset: FDUSD
    reserve-asset: USDT
    min-order-size: "5"
    price-tick-size: "0.01"
    qty-tick-size: "0.00001"

    risk:
      max-open-orders: "190"
      buy-orders-limit: "1"
      buy-wall-threshold-usd: "1000"
      target-margin: "1.0001"
      price-conflict-threshold: "0.00001"